server.port=8081
spring.application.name=rednorte-auth-service

# Base local H2 para trabajar sin PostgreSQL por ahora
spring.datasource.url=jdbc:h2:mem:rednorte_auth
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cuando quieran pasar a PostgreSQL, reemplazar por ejemplo:
# spring.datasource.url=jdbc:postgresql://localhost:5432/rednorte_auth
# spring.datasource.username=postgres
# spring.datasource.password=TU_PASSWORD
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
